<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="databaseApp.aspx.cs" Inherits="task8.databaseApp" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>

    <style>

        body {
            background: #B8E6CB;
        }


    </style>


</head>
<body>
    <form id="form1" runat="server">
        <div>


            <table>
                <tr>
                    <td>
                        <asp:Label ID="Label1" runat="server" Text="Name"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="TextName" runat="server" ></asp:TextBox>
                    </td>
                </tr>

                <tr>
                    <td>
                        <asp:Label ID="Label2" runat="server" Text="Role"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="TextRole" runat="server" ></asp:TextBox>
                    </td>
                </tr>
                
                <tr>
                    <td>
                        <asp:Label ID="Label3" runat="server" Text="Member since"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="TextMember" runat="server"></asp:TextBox>
                    </td>
                </tr>

                <tr>
                    <td>
                        <asp:Label ID="Label4" runat="server" Text="Email"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="TextEmail" runat="server" ></asp:TextBox>
                    </td>
                </tr>

                <tr>
                    <td>
                        <asp:Label ID="Label5" runat="server" Text="Id"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="TextId" runat="server" ></asp:TextBox>
                    </td>
                </tr>

                <tr>
                    
                    <td>
                        <asp:Button ID="Button1" runat="server" Text="Create new member" OnClick="Button1_Click" />
                    </td>
                </tr>
            </table>

            <br />

            <table>
                <tr>
                    <td>
                        <asp:Label ID="Label8" runat="server" Text="Search by name:"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="TextBox1" runat="server" ></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Button ID="Button2" runat="server" Text="Search" OnClick="Button2_Click" />
                    </td>
                
                </tr>
            </table>
            
            <br />

            <asp:Label ID="Label7" runat="server" Style="color:red"></asp:Label>


            <br />
            <br />

            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:empConnectionString %>" SelectCommand="SELECT * FROM [Employee]" DeleteCommand="DELETE FROM [Employee] WHERE Id =@Id" UpdateCommand="UPDATE [Employee] set Name=@Name, Role=@Role, MemberSince=@MemberSince, Email=@Email, Id=@Id WHERE Id=@Id"  ></asp:SqlDataSource>

            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="Id" DataSourceID="SqlDataSource1" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True">
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" ReadOnly="True" SortExpression="Id" />
                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                    <asp:BoundField DataField="Role" HeaderText="Role" SortExpression="Role" />
                    <asp:BoundField DataField="MemberSince" HeaderText="MemberSince" SortExpression="MemberSince" />
                    <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                </Columns>
            </asp:GridView>

            <br />
            <br />

            <asp:GridView ID="GridView2" runat="server"></asp:GridView>
            
            <br />
            <br />

            <asp:Label ID="Label6" runat="server"></asp:Label>
            <br />
            

            
            <br />
        </div>
    </form>
</body>
</html>
